### PR TITLE
Add mattress assortment field

### PR DESCRIPTION
**Pull request by garos4**

### CODE REVIEW

**Review by iamkarsoft — APPROVED** [review]

**Review by bmmage — APPROVED** [review]

**Review by OniiCoder — APPROVED** [review]

**Comment by tonning** [comment]
@garos4 I'm going to challenge you to find a way to accomplish this in a way that doesn't add specific knowledge of any of our sites to this Locations app. 
Think of the Locations app as a generic app that any other company or person can use and to them seeing a "mattress assortment" field would not make any sense. So see if you can find a creative/different/easy/smart/insert your own adjective here way to solve for the problem. Maybe we could make use of metafields in Stratasphere or some other solutions. But we should try to make these apps as generic as possible which will make it easier to use them for other brands/sites in the future.

You might even talk with @OniiCoder too, as he has faced similar challenges in the past also with this app.

**Comment by nrthbound** [comment]
> @garos4 I'm going to challenge you to find a way to accomplish this in a way that doesn't add specific knowledge of any of our sites to this Locations app. 
> 
> Think of the Locations app as a generic app that any other company or person can use and to them seeing a "mattress assortment" field would not make any sense. So see if you can find a creative/different/easy/smart/insert your own adjective here way to solve for the problem. Maybe we could make use of metafields in Stratasphere or some other solutions. But we should try to make these apps as generic as possible which will make it easier to use them for other brands/sites in the future.
> 
> 
> 
> You might even talk with @OniiCoder too, as he has faced similar challenges in the past also with this app.

In other words... Wax on, Wax off. Paint the fence, Daniel-San. - Miyagi out.

**Review by tonning — CHANGES_REQUESTED** [review]
@garos4 I just want to make sure you saw my previous comment and if you have any questions on how to go about it?

**Comment by garos4** [comment]
> @garos4 I just want to make sure you saw my previous comment and if you have any questions on how to go about it?

@tonning  This comment escaped me. Yes so I went the metafield route. So basically, they create a metafield for the mattress assortment text, logo svg and background color. So based on the values provided for the metafields, I render the locations section accordingly.

**Pull request closed without merging**
